### ISSUE TITLE
Wrong use of std::uniform_int_distribution

### ISSUE THREAD

**Issue by ishitatsuyuki** [boostorg/fiber#103]
`std::uniform_int_distribution` is a stateful class. Please do not initialize it at every random call.

Example:
https://github.com/boostorg/fiber/blob/master/src/algo/work_stealing.cpp#L61

**Comment by olk** [comment]
The distributions like std::uniform_real_distribution can be as short-lived as you want. They're plain functors where the constructor either has no arguments or only stores the arguments for when the functor gets executed.

**Comment by ishitatsuyuki** [comment]
Not sure if I understood what you mean, but `std::uniform_int_distribution` definitely has internal states. If you are discarding them every time, you will get the wrong behavior.

**Comment by olk** [comment]
As Stephen T. Lavavej (member of the standard committee) suggested at GoingNative 2013 to simply create new distributions as it is required (for instance variation of the distribution range) - it shouldn't be a performance issue.

**Comment by ishitatsuyuki** [comment]
If you do that, you are losing the uniform part; it's simply a alphabet-only way of mod(%). Since keeping it doesn't incur much overhead too, why don't you consider storing it statically?

**Comment by olk** [comment]
```
static thread_local std::minstd_rand generator;
	std::size_t idx = 0, max_idx = 8;
	for ( int i = 0; i < 10; ++i) {
		std::cout << i << ": " << std::uniform_int_distribution< std::size_t >{ 0, max_idx }( generator) << std::endl;
	}
```

0: 0
1: 0
2: 5
3: 8
4: 8
5: 1
6: 4
7: 3
8: 2
9: 6

**Comment by ishitatsuyuki** [comment]
Seems you're right; the internal implementation most time doesn't rely on the state.

However, it's not considered a good practice to rely on implementation details; also, I think it's better to do this instead of spin attacking:
```
if(idx>=idx_) ++idx; // Note that the max should be reduced by 1
```

**Comment by olk** [comment]
In my tests simple increment of idx was less performant than using random numbers
