### ISSUE TITLE
Compile error on ARMv6

### ISSUE THREAD

**Issue by vdav** [boostorg/fiber#110]
Some ARM processors do not support "yield" instruction used in include/boost/fiber/detail/cpu_relax.hpp.

Compilation with GCC will generate error messages such as:

/tmp/ccUV8Ii4.s: Assembler messages:
/tmp/ccUV8Ii4.s:2171: Error: selected processor does not support ARM mode `yield'

This problem will happen on Raspbian (-march=armv6) and Debian armel (-march=armv4t I believe) for example.

**Comment by olk** [comment]
Do you know an equivalent to x86 'pause' mnemonic?

**Comment by vdav** [comment]
There is no multi-core prior to armv6k. So I do not think there are any equivalent since you are not suppose to use spin-locks on those.

**Comment by olk** [comment]
'pause' is used to prevent pipeline stalling - so it does not depend on multi-core support

**Comment by olk** [comment]
fixed in branch develop - on Odroid-X (ARMv7) it is working.
Could you check the fix on your device please - you should see a warning that the platform doesn't support yield/pause.
ty
