### ISSUE TITLE
endless-loop in buffered_channel::try_value_pop()

### ISSUE THREAD

**Issue by tschuett** [boostorg/fiber#111]
I am calling try_value_pop() in the buffered channel and end up in an endless loop.

``
try_pop_: full=0 empty=0 capacity=1 closed=0 producers=0 consumers=0 consumer_idx_=0 slots_[0].cycle.load()=2
``

My guess is that ``idx`` is 0 in ``try_value_pop_()``. ``diff`` is 1 (2-(idx+1)) and the loop reloads ``consumer_idx_`` which is 0.

Do you have any ideas how I ended up here? Thanks in advance.

**Comment by olk** [comment]
I'm wondering, buffered_channel doesn't have a try_value_pop() member function.

**Comment by tschuett** [comment]
My bad. I called try_pop (https://github.com/boostorg/fiber/blob/master/include/boost/fiber/buffered_channel.hpp#L374) which calls try_pop_ (https://github.com/boostorg/fiber/blob/master/include/boost/fiber/buffered_channel.hpp#L120) which calls try_value_pop_(https://github.com/boostorg/fiber/blob/master/include/boost/fiber/buffered_channel.hpp#L99). Here I ran in the endless loop.

**Comment by olk** [comment]
could you provide test-code that demonstrates your problem

**Comment by tschuett** [comment]
Here is the reproducer. The last output I get is:
``ct2_inner calling tryp_pop``
``try_pop_: full=0 empty=0 capacity=1 closed=0 producers=0 consumers=0 consumer_idx_=0 slots_[0].cycle.load()=2``
The try_pop call never returns.

[reproducer.zip](https://github.com/boostorg/fiber/files/798921/reproducer.zip)

**Comment by olk** [comment]
buffered_channel's capacity must be a power of two - I've changed the test in the constructor

**Comment by jondo2010** [comment]
I have a use case for a capacity of 1, is it possible to relax this power-of-2 requirement?

**Comment by olk** [comment]
Unfortunately no - buffered_channel requires a capacity of power of two because positions inside the buffer are calculated via shift operations (for performance reasons).

What is your use case for a capacity of two? Maybe unbuffered_channel is a option?
