### ISSUE TITLE
protected class members for shared_work scheduler

### ISSUE THREAD

**Issue by danichcr72** [boostorg/fiber#112]
Hi,

  First of all, thanks for the great contributions of fibers to the boost libraries!

  I used fibers to build a runtime system for a distributed database system and had the need to create a custom scheduler.  The scheduler that I needed was pretty similar to your provided shared_work scheduler with the caveat that the "system" or dispatcher fibers must be scheduled with some frequency to garbage-collect terminated tasks.  I proceeded to derive my scheduler from your shared_work but unfortunately needed to change your code to declare the members of the shared_work class to be **protected** instead of **private**.

  Would it be possible to change these class members to be protected so that they can be accessed by derived classes?

Thanks,

Daniel Chavarria
Trovares Inc.

**Comment by olk** [comment]
I plan to re-factor the API for custom-schedulers - but unfortunately I'm very busy.

**Comment by olk** [comment]
related to #113

**Comment by olk** [comment]
Please, use work_stealing scheduler instead of shared_work. work_stealing is much faster and does schedule dispatcher fibers correctly.
