### ISSUE TITLE
Garbage collection of completed tasks

### ISSUE THREAD

**Issue by danichcr72** [boostorg/fiber#113]
Hi,

  Another general issue that appeared in my experience with fiber is that completed tasks do not release their memory until the dispatcher/system fiber runs.

  The dispatcher fiber is not scheduled in all (?) / most(?) schedulers unless there are no application fibers pending.  It would be great to provide another mechanism to garbage collect completed tasks, either by the user calling a function or by having the dispatcher fiber scheduled with some other priority.

Thanks,

Daniel Chavarria
Trovares Inc.

**Comment by olk** [comment]
One of the tasks of the dispatcher-fiber is to release terminated worker-fibers  (== fibers created by the user-code). The dispatcher-fiber is the first fiber in the ready-queue when the application/thread starts. It always enqueues itself before it hands-over to another worker-fiber (dequeued from the ready-queue).
So the dispatcher-fiber should be executed multiple times in your app.

**Comment by danichcr72** [comment]
Thanks for the quick reply.  I can see that the dispatcher fiber is scheduled to run, however in the shared_work scheduler at least, it does not run unless there are no worker fibers pending:

    if ( ! rqueue_.empty() ) { /*<
            pop an item from the ready queue
        >*/
        ctx = rqueue_.front();
        rqueue_.pop_front();
        lk.unlock();
        BOOST_ASSERT( nullptr != ctx);
        context::active()->attach( ctx); /*<
            attach context to current scheduler via the active fiber
            of this thread
        >*/
    } else {
        lk.unlock();
        if ( ! lqueue_.empty() ) { /*<
                nothing in the ready queue, return main or dispatcher fiber
            >*/

**Comment by olk** [comment]
right - shared_work was previously in the examples , so I missed the implementation details

**Comment by olk** [comment]
releated to #113

**Comment by olk** [comment]
The problem is that the dispatcher-fiber is not correctly scheduled in the shared_work algo.
If you take a look at work_stealgin algo (branch develop) you see that the dipatcher-fiber is scheduled like in round_robin.
I suggest to switch to work_stealing because it is faster (locality of data) than shared_work.
Otherwise shared_work needs some counters that manage teh scheduling of main-/dispatcher-fiber ...

**Comment by olk** [comment]
use work-stealing scheduler instead
