### ISSUE TITLE
Is there a version of boost.fiber that will work with the TS version of ASIO?

### ISSUE THREAD

**Issue by akoolenbourke** [boostorg/fiber#137]
With the github ASIO master branch having modifications for the networking TS, will (is) there be a branch/fork of fiber will be compatible with that?

**Comment by olk** [comment]
which changes of boost.asio?

**Comment by olk** [comment]
change log for boost-1.65 does not contain asio

**Comment by akoolenbourke** [comment]
Sorry if I wasn't clear, I wasn't asking about Boost.ASIO but ASIO. ASIO master branch is ASIO with changes to reflect the networking TS. I was wondering if there were any plans to make something like Boost.Fibre compatible with that in any way, i.e. how ASIO itself comes in Boost and non-Boost versions.

Boost Fiber looks very interesting but we have decided to go with the TS version of ASIO for our async IO.

**Comment by olk** [comment]
Ok, I could try to provide some fiber integration for asio

**Comment by olk** [comment]
you refer to https://github.com/chriskohlhoff/networking-ts-impl, right?

2017-07-20 10:40 GMT+02:00 akoolenbourke <notifications@github.com>:

**Comment by vinipsmaker2** [comment]
Boost.Asio 1.66 was released with TS-changes as well: http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/net_ts.html

**Comment by randian** [comment]
Since the Networking TS version of ASIO is basically, if not formally, deprecated in Boost 1.74 in favor of standard executors, how would one write a standard executor style fiber executor? The boost fiber io_service integration definitely won't work.

**Comment by olk** [comment]
I'm too busy but you are welcome to provide a fiber executor via pull request.
