### ISSUE TITLE
Tests fail on gcc-4.8, clang-3.9 on Travis

### ISSUE THREAD

**Issue by pdimov** [boostorg/fiber#147]
See https://travis-ci.org/boostorg/boost/jobs/287409126 and https://travis-ci.org/boostorg/boost/jobs/287409127

Not sure if this is relevant, but in any case.

**Comment by pdimov** [comment]
Many failures have been fixed, but one remains:

```
testing.capture-output bin.v2/libs/fiber/test/test_topology.test/gcc-gnu-4.8/release/cxxstd-11-iso/link-static/threadapi-pthread/threading-multi/test_topology.run
====== BEGIN OUTPUT ======
Running 1 test case...
unknown location(0): fatal error: in "Boost.Fiber: numa topology test suite/_test_topology": std::regex_error: regex_error
libs/fiber/test/test_topology.cpp(21): last checkpoint
*** 1 failure is detected in the test module "Master Test Suite"
EXIT STATUS: 201
====== END OUTPUT ======
```

**Comment by olk** [comment]
boost.fiber doesn't use std::regex - must be a bug of gcc-4.8

**Comment by pdimov** [comment]
Pretty mysterious how

```
    BOOST_CHECK( ! boost::fibers::numa::topology().empty() );
```

can result in a `std::regex_error`, yes. Probably not worth it to investigate though. :-)

**Comment by olk** [comment]
I've had changed the unit-test to:
```
bool empty = boost::fibers::numa::topology().empty();
BOOST_CHECK( ! empty);
```

Should be in branch master and develop ?!

**Comment by pdimov** [comment]
You're right, my local repo was behind. The latest fiber does indeed contain what you say. It still fails with

```
testing.capture-output bin.v2/libs/fiber/test/test_topology.test/gcc-gnu-4.8/release/cxxstd-11-iso/link-static/threadapi-pthread/threading-multi/test_topology.run
====== BEGIN OUTPUT ======
Running 1 test case...
unknown location(0): fatal error: in "Boost.Fiber: numa topology test suite/_test_topology": std::regex_error: regex_error
*** 1 failure is detected in the test module "Master Test Suite"
EXIT STATUS: 201
====== END OUTPUT ======
```

that is, the exception is thrown by `boost::fibers::numa::topology()`.

Looking at https://github.com/boostorg/fiber/blob/develop/src/numa/linux/topology.cpp#L42, you do use `std::regex`, so that's one mystery fewer. :-)

**Comment by pdimov** [comment]
Would you like me to enable Travis here and add a `.travis.yml` file?

**Comment by olk** [comment]
Yes, would be nice (I've never used travis so far).

**Comment by pdimov** [comment]
https://travis-ci.org/boostorg/fiber/builds/298010277

Looks like a problem with `<regex>` on libstdc++-4.8.

**Comment by olk** [comment]
OK. My first guess was that something with the BOOST_CHECK macro was going wrong (I forgot the code evaluating the NUMA part on Linux uses std::regex ... the code was written long time ago).

I'm using Arch Linux, so I've the newest gcc and I'm too lazy to setup a qemu for gcc-4.8.

Do you agree, that we don't fix it?

**Comment by pdimov** [comment]
Boost.Config says

```
#if (BOOST_LIBSTDCXX_VERSION < 40900) || !defined(BOOST_LIBSTDCXX11)
// Although <regex> is present and compilable against, the actual implementation is not functional
// even for the simplest patterns such as "\d" or "[0-9]". This is the case at least in gcc up to 4.8, inclusively.
#  define BOOST_NO_CXX11_HDR_REGEX
#endif
```

so that's that. You could disable `test_topology.cpp` in the Jamfile, although the correct condition (`requires cxx11_hdr_regex` but only on Linux) is a bit hard to express. `<toolset>gcc-4.8:<build>no` is always an option, I suppose.

**Comment by olk** [comment]
Ty, I'll use the defect featreue macro.

**Comment by pdimov** [comment]
Do you support OS X? It doesn't seem to work. https://travis-ci.org/boostorg/fiber/builds/298295344

**Comment by olk** [comment]
I don't have access to a MacOS X system - the error is caused because ucontext is deprecated by POSIX but most systems still keep it. Seams that Apple has skipped the support or I've not added the right code to enable it (_XOPEN_SOURCE_).

**Comment by pdimov** [comment]
`ucontext` just causes warnings, but things fail, for different reasons on the different Xcode versions.

If OS X is unsupported, I'll remove it from Travis, as there's no reason to keep testing it.

**Comment by olk** [comment]
OS X is supported for the assembler implementation, but ucontext seams to fail.
It seams not so easy to express the negation of OS X in the Jamfile for the unit-tests.

```
test-suite native :
[ run test_fiber_post.cpp :
    : :
    <conditional>@configure-impl
    [ requires cxx11_auto_declarations
               cxx11_constexpr
               cxx11_defaulted_functions
               cxx11_final
               cxx11_hdr_mutex
               cxx11_hdr_thread
               cxx11_hdr_tuple
               cxx11_lambdas
               cxx11_noexcept
               cxx11_nullptr
               cxx11_rvalue_references
               cxx11_template_aliases
               cxx11_thread_local
               cxx11_variadic_templates 
               ! mac_os_x]
    : test_fiber_post_native ]
```

**Comment by pdimov** [comment]
To disable something on OS X, you probably need to use `<conditional>` that returns `<build>no` depending on `<target-os>`.

**Comment by olk** [comment]
pushed - <target-os>macosx seams not to be right, I've used <target-os>darwin instead

**Comment by pdimov** [comment]
There's still

```
testing.capture-output bin.v2/libs/fiber/test/test_topology.test/clang-darwin-darwin-4.2.1/release/cxxstd-11-iso/link-static/threadapi-pthread/threading-multi/test_topology.run
====== BEGIN OUTPUT ======
Running 1 test case...
unknown location:0: fatal error: in "Boost.Fiber: numa topology test suite/_test_topology": boost::fibers::fiber_error: boost fiber: topology() not supported: Function not implemented
*** 1 failure is detected in the test module "Master Test Suite"
EXIT STATUS: 201
====== END OUTPUT ======
```

Rest seems to work on xcode 8, 8.1; the others are still pending.

**Comment by olk** [comment]
Right, I forgott that Mac OS X doesn'*t support NUMA - unit-test is disabled now.
Ty.
