### ISSUE TITLE
Complete numa support with numa aware memory alloc

### ISSUE THREAD

**Issue by WeissGotsman** [boostorg/fiber#148]
please include cross platform numa aware memory alloc. It looks like it already exists on your another deprecated boost-job project.

this is because on a numa system we may always need to set thread affinity for optimal locality of memory access, which means numa aware memory alloc is already there, and for the sake of completeness it's better for fiber to offer such support.

Also, it's better to offer an interface that allow setting thread affinity outside the current thread, i.e. on a main thread scheduler.

**Comment by olk** [comment]
NUMA memory allocation is not portable ... you have greate difference in supported options (interleaved, strict ...).
A alaternative is to set the default NUMA allocation policy for the process and use normal functions (malloc() etc.) for memory allocation - or - use platform specific NUMA functions.

**Comment by WeissGotsman** [comment]
No, your if else macro made it portable

**Comment by olk** [comment]
I'm too busy - but you are welcome to provide a pull-request.
