### ISSUE TITLE
Crashes on Windows

### ISSUE THREAD

**Issue by qiaone** [boostorg/fiber#151]
**Tested Platforms:**
1, A Lenovo laptop with Win 8.1 VS2015 update 3
2, A Macbook Pro laptop with Win 8.1 VS2017.2
3, A Intel Core i5 16GB RAM desktop with Win7 VS2017.2
4, A Intel Core i5 8GB RAM desktop with Win8.1 VS2015 update 3

**Tested Versions:**
1, Boost 1.65.1
2, Boost 1.65.1 + Dev branch of Boost.Context and Boost.Fiber
3. Boost 1.64.0

**Build Config:**
`b2 variant=debug threading=multi link=static runtime-link=static address-model=64 stage`

**VS Config:**
1, Debug build
2, Static linking of the C++ runtime
3, Stack reserved size increased to 4M/8M/16M but not helped

**Code:**
All the code samples from the  `performance/fiber` in the repo crashed.
```
fiber/performance/fiber/skynet_detach.cpp
fiber/performance/fiber/skynet_join.cpp
fiber/performance/fiber/skynet_shared_detach.cpp
...
```

**Call stacks screenshots:**

<img width="651" alt="snipaste_20171106_005103" src="https://user-images.githubusercontent.com/5222364/32413485-089f645a-c24d-11e7-92b8-c36370241274.png">

<img width="734" alt="snipaste_20171106_005304" src="https://user-images.githubusercontent.com/5222364/32413489-16d14782-c24d-11e7-83ff-6070efdb47eb.png">

<img width="751" alt="snipaste_20171106_005352" src="https://user-images.githubusercontent.com/5222364/32413491-1c246d86-c24d-11e7-82da-830a4f10b482.png">

<img width="659" alt="snipaste_20171106_005531" src="https://user-images.githubusercontent.com/5222364/32413493-21b0fbe8-c24d-11e7-986a-f08973275d72.png">

**Comment by olk** [comment]
"The maximum number of stack frames supported by Visual Studio hasbeen exceeded." ?

**Comment by qiaone** [comment]
Yeah, I think it's a limitation of the VS debugger which lead to incomplete display of the callstacks. But the code in work_stealing::pick_next() do crashes a lot with various callstacks.

**Comment by olk** [comment]
I don't use Windows, my development platform is Linux and its does not crash even if I execute skynet_stealing_detach in a loop for hours.
You could try to enable the WinFiber support : compile boost.context + boost.fiber with context-impl=winfib.

**Comment by olk** [comment]
Maybe VC adds TLS and if a fiber is migrated to another thread you will get a crash.

**Comment by qiaone** [comment]
I finally got all code samples working using WinFiber as you suggested. I'll try to look into the problem and hopefully find some clues why it crashes when using fcontext. Thanks for all the help.

**Comment by olk** [comment]
Another reason could be the TIB (thread information block) which is not fully described in MSDN. Maybe some special parts are not swapped in the assembler impl of boost.context (Gor Nishanov has told me  something ...).
