### ISSUE TITLE
Many examples are using their own barrier.hpp

### ISSUE THREAD

**Issue by ldionne** [boostorg/fiber#156]
It seems like the library is also providing the same `barrier` class. Should the examples be using `<boost/fiber/barrier.hpp>`, or is there a subtle reason for them not to? As a novice trying to get his program to work, I found that confusing as I don't know which one to use (and whether that may be the cause for my program not working).

**Comment by ldionne** [comment]
Ah! I just changed `::barrier` to `boost::fibers::barrier` in the work stealing example and it starts segfaulting at the end of the program. So I guess there _is_ a difference.

**Comment by olk** [comment]
examples work_sharing and work_stealing using barrier in order to synchronize (scheduling-algo) the worker-threads

**Comment by ldionne** [comment]
So, the only difference is that one of them is using `boost::fibers::condition_variable` and the other one is using `std::condition_variable`, right? Would it be possible to rename the one used in examples to `thread_barrier` or something like this, then? This is a trap waiting to bite any novice that's copy/pasting examples when experimenting (such as myself).

**Comment by olk** [comment]
done
