### ISSUE TITLE
Fiber launch policy: unlinked

### ISSUE THREAD

**Issue by mtanski** [boostorg/fiber#169]
Right now when a fiber is a created it's either launched right away or put in the run queue on the current scheduler. In some cases it I may need to delay launching the fiber (because I want to start it on a different scheduler like CPU bound work scheduler).

This might be easily done if there's a policy that doesn't link it to the current scheduler / doesn't put it in the run queue. This way it can be manually added to another scheduler.

**Comment by olk** [comment]
Ty for your suggestion, I've to think about it - but I'm busy at the moment

**Comment by olk** [comment]
it is not possible with the current design (schedulers are implicit at the moment)
