### ISSUE TITLE
buffered_channel::try_push has incorrect documentation

### ISSUE THREAD

**Issue by ldionne** [boostorg/fiber#170]
The documentation for `buffered_channel::try_push` says:

> If channel is closed, returns closed. Otherwise enqueues the value in the channel, wakes up a fiber blocked on `this->pop()`, `this->value_pop()`, `this->pop_wait_for()` or `this->pop_wait_until()` and returns success.

However, this is the behavior of `buffered_channel::push`. The behavior for `try_push` should be to return `full` without blocking when the channel is full. The implementation of `try_push` seems to agree with me.

**Comment by olk** [comment]
> wakes up a fiber blocked on this->pop(), this->value_pop(), this->pop_wait_for() or this->pop_wait_until()

is correct ... it needs only an addtional description what happens if the channel is full

**Comment by olk** [comment]
ty

**Comment by rkfg-bc** [comment]
In 1.68 it's changed wrongly, now the `try_push` and `push` description is exactly the same while `push` actually blocks if the buffer is full. The documentation says it doesn't block.
