### ISSUE TITLE
How does one emulate c++11 thread_local but for fibers (Fiber Local Storage)?

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [boostorg/fiber#179]
Since a fiber may wake up on a different thread, thread_local is useless.

I have a few std:: compatible allocators which use thread_local in order to be lockless, however they would break if used with fibers.

I know that windows has Fiber Local Storage, is there any way to do this in boost?

**Comment by olk** [comment]
You could use fiber_specific_ptr: https://www.boost.org/doc/libs/1_68_0/libs/fiber/doc/html/fiber/fls.html

**Comment by devshgraphicsprogramming** [comment]
Is there no faster way to do it than a lookup in an std::map !?

I mean at least on windows it would perform far faster using the built-in system API.

**Comment by devshgraphicsprogramming** [comment]
On a note, if all global/static fiber-local variables would be declared via a wrapper class that supported some metaprogramming and manipulation of a global counter through the static object's initializers then the total space required for all `thread_local`-like could be known either at compile-time or at least just before `main()` would be called. 

So it would be possible to prepend "shadow stack space" to the allocated context's stack and retrieve all FLS variables by simple arithmetic in almost exactly the same way as TLS works.

**Comment by olk** [comment]
You can only use the Win-Fiber API if boost.context uses it as its implementation detail (property win-fib). - otherwise it's not possible. On Linux/Unix you don't have an system API that provides fiber-local-storage.
