### ISSUE TITLE
Async IO / operation with "Event" without callback mechanism

### ISSUE THREAD

**Issue by KaoCC** [boostorg/fiber#180]
Hello.

I'd like to ask how to integrate fiber with other frameworks that include asynchronous I/O API but only return an "event" to be wait for (the wait will block the thread). These frameworks may not have the APIs for registering a proper callback function.

Imagine a simple example as an OpenCL wrapper that wraps clEnqueueNDRangeKernel but did not expose the clSetEventCallback functionality.

In addition, for Boost.Compute can we register a fiber promise which is to be invoked in a callback in the ".then(Callback)" function which is from the future returned by "copy_async" ?

**Comment by olk** [comment]
bosot.fiber will not work with frameworks that block the thread ... if a thread is blocked no other ready fiber can be executed.

In context of accelerator APIS - take a look at the CUDA/HIP examples. The thread is not blocked while some fiber wait on events from CUDA/HIP streams.

**Comment by KaoCC** [comment]
Thank for the reply !
