### ISSUE TITLE
why lockless implementation of remote queue has been cancelled?

### ISSUE THREAD

**Issue by romange** [boostorg/fiber#197]
Hi Oliver, 

do you remember why you erased Vyukov's lockless queue for remote-ready use-case?
https://github.com/boostorg/fiber/commit/0d62d7c5d25a203c1a261a2884067b689c364c4c

Incidentally, I've added it to my version of fibers lib and only then discovered you've already tried it...

**Comment by olk** [comment]
I can't remember - sorry (probably because of performance issues)
