### ISSUE TITLE
handler_type deprecation

### ISSUE THREAD

**Issue by yowidin** [boostorg/fiber#201]
As of Boost 1.70.0 the `handler_type` type trait is now removed (it was deprecated before) so the ASIO-based examples no longer compile:
> The previously deprecated handler_type trait and single-argument form of async_result have now been removed. 

Can you please update the yield examples to use `async_result` instead?

I tried to fix the `detail/yield.hpp` definitions myself by I honestly can't handle this level of template programming magic.

**Comment by Warchant** [comment]
After trial and errors I've come up with this: 
https://gist.github.com/Warchant/d58dc2aecc500ee5fce71ff92a2ba094

More experienced boost devs may use this as a reference, and then submit a PR to close this issue.

**Comment by olk** [comment]
fixed
