### ISSUE TITLE
When <C++11 is used, build/configuration step should fail

### ISSUE THREAD

**Issue by Warchant** [boostorg/fiber#204]
- Mac OS 10.14.4
- Boost 1.70.0

```
1. git clone --recursive https://github.com/boostorg/boost
2. cd boost
3. ./bootstrap --with-libraries=chrono,thread,filesystem,system,thread,fiber
4. ./b2
```

**Actual behaviour**: For some reason C++98 standard is used by default. Build *succeeds*, and `stage/libs` does not contain `libboost_fiber*.{a,dylib}`. 

**Expected behaviour**: build fails with message "you're using C++98, but minimal requirement for Boost.Fiber is C++11".

**Comment by olk** [comment]
If compiling one boost lib fails - why would you abort compiling the other boost libs?
You have to address this to boost.build.
