### ISSUE TITLE
Is it possible to replace default scheduler implementation with the custom one?

### ISSUE THREAD

**Issue by Warchant** [boostorg/fiber#207]
Is it possible to replace [default scheduler](https://sourcegraph.com/github.com/boostorg/fiber@develop/-/blob/src/context.cpp#L78) implementation with the custom one somehow? Without forking this repo.

**Comment by olk** [comment]
no, it's not possible - you can customize the scheduling algorithms (round-robin, priority, work-stealing, work.sharing, ...) by your own.
