### ISSUE TITLE
dead loop when all worker fibers done

### ISSUE THREAD

**Issue by rockeet** [boostorg/fiber#210]
I created N-1 worker fiber and use main fiber as the last worker fiber, when things done, it hang in dispatch sometime(at low frequency).

Then I create N worker fibers, and yield in main fiber to wait all workers, the hang disappeared.

**Comment by olk** [comment]
without code I can't say much ....

**Comment by rockeet** [comment]
The code is very long..., and I failed to write a minimized reproduce test case.

It should caused by a thread(say thread A) is finished earlier than its fibers, and another thread B call thread A's fiber.join(). I changed my code and it's OK now.

**Comment by olk** [comment]
fine
