### ISSUE TITLE
#include <iostream>

### ISSUE THREAD

**Issue by dixlorenz** [boostorg/fiber#216]
I just noticed context.hpp includes <iostream>. Wouldn't <iosfwd> be enough? Or some other solution? context.hpp is practically used by ever other header file, it permeates the whole build and really, fibers have nothing to do with IO, it shouldn't incur that cost.

**Comment by dixlorenz** [comment]
grumble. Something stripped out the header names :-) it does include "iostream" and I think "iosfwd" should be enough...

**Comment by olk** [comment]
fiber::id has an shift op. for output
