### ISSUE TITLE
The ASIO example failed to build  with boost 1.71

### ISSUE THREAD

**Issue by zhmt** [boostorg/fiber#219]
I failed to make things right, Can you correct it please?

**Comment by zhmt** [comment]
handler_type has been removed since boost_1_70_0

**Comment by olk** [comment]
could you provide a pull request please, I'm too busy at the moment

**Comment by zhmt** [comment]
I don't know how to integrate asio with fiber exactly,  I tried, but failed.
I will try again.
Thank you for your response.

**Comment by olk** [comment]
fixed
