### ISSUE TITLE
Can fibers::shared_future<T>::get() be called multiple times?

### ISSUE THREAD

**Issue by ingomueller-net** [boostorg/fiber#224]
I suppose that the answer is yes; it seems like that is the point of `shared_future`. See also [this SO discussion](https://stackoverflow.com/questions/56756112/is-it-legal-to-call-shared-futureget-multiple-times-on-the-same-instance-in) why it seems to be allowed in `boost::shared_future` and `std::shared_future`. Finally, I tried it out and it seems to work.

However, this seems to contradict the documentation of [`shared_future<T>::get()`](https://www.boost.org/doc/libs/1_72_0/libs/fiber/doc/html/fiber/synchronization/futures/future.html#shared_future_get), which defines the post-condition `false == valid()`. Is the documentation wrong or am I misunderstanding something?

**Comment by olk** [comment]
yes - docu mus be fixed
