### ISSUE TITLE
emscripten support?

### ISSUE THREAD

**Issue by unicomp21** [boostorg/fiber#238]
Given webassembly currently doesn't have couroutine support, being able to use boost fibers from emscripten would be awesome!!!

**Comment by unicomp21** [comment]
I believe clang can emit webassembly now, could we have webassembly target?

**Comment by Akaricchi** [comment]
For the record, Emscripten now has [a low-level fiber API](https://emscripten.org/docs/api_reference/fiber.h.html) since 1.39.7. It could be used as a backend for boost fibers.

**Comment by olk** [comment]
belongs to boost.context
