### ISSUE TITLE
Question about the processing loop in boost::fibers::asio::round_robin

### ISSUE THREAD

**Issue by randian** [boostorg/fiber#267]
Assume I am the last running fiber for the thread executing io_context->run(), the same io_context that round_robin posted a handler-processing lambda to. What must that fiber do to ensure the "while (!io_ctx_->stopped()) {" loop exits when it exits, which should release the thread from run() since it's the last handler? I've tried to just exit the fiber for a clean shutdown but that merely seems to hang my program.

**Comment by olk** [comment]
Not sure about your code - at least if a fiber is waiting/blocked for some event it must be woken up.

**Comment by randian** [comment]
> Not sure about your code - at least if a fiber is waiting/blocked for some event it must be woken up.

How does the loop ever exit? It looks like there is either a pending timer created by suspend_until which needs to be handled when the main fiber wakes up in branch A or, if all fibers other than the main fiber running the loop have exited, in branch B run_one() will wait forever for work to be posted, which will never happen because all running fibers other than the main fiber have exited.

**Comment by olk** [comment]
`io_ctx_->stopped()` will return `true` if `io_ctx_->stop()` has been called.

**Comment by randian** [comment]
> `io_ctx_->stopped()` will return `true` if `io_ctx_->stop()` has been called.

So to get a clean shutdown the last running fiber needs to ensure all other fibers have exited, then call stop() just before it exits?

**Comment by olk** [comment]
Take a look at the examples.
