### ISSUE TITLE
error 1 while executing b2.exe

### ISSUE THREAD

**Issue by gyorokpeter** [boostorg/fiber#278]
I'm trying to build [yuzu](https://github.com/yuzu-emu/yuzu/wiki/Building-For-Windows) using the instructions for MSYS2. I got up to this command:
```cmake -G "MSYS Makefiles" ..```
But this command seems to fail during the boost build.

I have attached the full output of the command.
[output.txt](https://github.com/boostorg/boost/files/6799594/output.txt)

**Comment by olk** [comment]
std::thread::native_handle_type == Returns the implementation defined underlying thread handle. 
MSDN: native_handle_type is defined as a Win32 HANDLE that's cast as void * (https://docs.microsoft.com/en-us/cpp/standard-library/thread-class?view=msvc-160). 

But mingw64/STL implementation does  define std::thread::native_handle_type as 'long long unsigned int' which is false as the e Microsoft documentation states.

So ming64/your STL implementation has to be fixed.

**Comment by gyorokpeter** [comment]
Just to confirm, am I doing this right?
Currently ```thread``` looks like this:
```
typedef __gthread_t native_handle_type;
```
And there are two different files where ```__gthread_t``` is defined: ```bits/gthr-default.h``` and ```gthr-posix.h```. In both this is defined as
```
typedef pthread_t __gthread_t;
```
```pthread_t``` is defined in ```pthread.h```:
```
typedef uintptr_t pthread_t
```
Should I change this to:
```
typedef void* pthread_t;
```

**Comment by grisumbras** [comment]
It's not something you need to change. It's something MinGW devs need to change. Alternatively, maybe yuzu devs know how to handle this issue.

**Comment by olk** [comment]
AFAIK mingw is a port of gcc to Windows. gcc has its origin on POSIX systems.
Function SetThreadGroupAffinity() used in boost.fiber is a function of the Windows native API. It might be that mingw can not be used together with parts of the Windows native API because of some incompatibilities.
