### ISSUE TITLE
Boost::fiber's library doesn't seem to get built in 1.78

### ISSUE THREAD

**Issue by 20k** [boostorg/fiber#287]
Hi there. Compiling boost under wsl2 (ubuntu) with GCC-10 doesn't seem to produce any libboost_fiber libraries on 1.78. 1.76 seems to work fine

The command line I used for both was: ./b2 -j32 variant=release link=shared threading=multi runtime-link=shared

Variations of --with-fiber, or cxxflags="-std=c++14" (as well as 11 and 17) did not cause boost to build the library. It reports as a success, but there's simply no shared object at the end of it. In the end I reverted to 1.76, which correctly builds

Thanks!

**Comment by olk** [comment]
Can't reproduce your problem:
- gcc-11
- arch linux
- ./b2 --with-fiber -j 25
- library at: bin.v2/libs/fiber/build/gcc-11/release/threading-multi/visibility-hidden/libboost_fiber.so.1.78.0

**Comment by 20k** [comment]
Interesting, I didn't think to check under bin.v2/libs/fiber/build/gcc-10/release/threading-multi/visibility-hidden/

In 1.78 libboost_fiber.so.1.78.0 is built there successfully, but there's nothing under ./stage/lib and boost fiber fails to install correctly. In 1.76 the .so is produced both in the bin.v2 segment, as well as in ./stage/lib along with the corresponding symlinks. It looks possibly like some kind of failure of the build system

**Comment by 20k** [comment]
This looks like its probably the same issue as https://github.com/boostorg/boost/issues/594 and #286

**Comment by olk** [comment]
I think this issue is related to the cmake stuff.

**Comment by brad0** [comment]
This is probably related to the  known issues listed item..

https://www.boost.org/patches/1_78_0/0001-b2-fix-install.patch
