### ISSUE TITLE
Warning/error about unreferenced parameter in context.cpp

### ISSUE THREAD

**Issue by mojca** [boostorg/fiber#302]
When building the code on Windows with MSVC 2022 with "treat warnings as errors" I'm getting the following error:
```
C:\build\__external\src\boost\libs\fiber\src\context.cpp(33,36): error C2220: the following warning is treated as an error [C:\build\_deps\boost-build\libs\fiber\boost_fiber.vcxproj]
C:\build\__external\src\boost\libs\fiber\src\context.cpp(33,36): warning C4100: 'c': unreferenced formal parameter [C:\build\_deps\boost-build\libs\fiber\boost_fiber.vcxproj]
```
https://github.com/boostorg/fiber/blob/3e1770607c88a7a67869bd50fdd70f6da7be19c0/src/context.cpp#L33-L39

**Comment by olk** [comment]
fixed, ty

**Comment by mojca** [comment]
Thank you very much.
Would it be possible to include this into the 1.81 release?
