### ISSUE TITLE
Launching fiber on a different thread

### ISSUE THREAD

**Issue by beojan** [boostorg/fiber#311]
I'd like to launch fibers on a pool of worker threads, but not the main thread. Currently, I'm using `shared_work` scheduler in all the threads, launching fibers with `launch::post` and simply not calling `this_thread::yield` from the main thread in the hope that the fibers will just get scheduled on one of the workers (which are waiting on a condition variable). However, it seems with this setup my fibers never run at all.

**Comment by beojan** [comment]
Turns out I was actually trying to launch from a thread where I hadn't set the scheduler. Nevertheless, it would be nice to be able to launch fibers on other threads.

**Comment by olk** [comment]
Unfortunately you always need a scheduler, it is not possible to use fibers without a scheduler.

**Comment by beojan** [comment]
I'm not looking to launch fibers without a scheduler, I'm looking to launch
fibers on a thread other than the one I'm launching from.
