### ISSUE TITLE
movable channels?

### ISSUE THREAD

**Issue by cinghiale** [boostorg/fiber#71]
Both bound and unbound channels are not copyable nor movable, and thus it cannot be used with std container.

It's possible to make a channel movable or I have to resort to a vector of [shared|unique] pointers?

**Comment by olk** [comment]
(un)bounded_channel uses condition_variable which is not CopyConstructible, MoveConstructible, CopyAssignable, MoveAssignable (as their counterpart in std-namespace).
at the moment you have to use shared/unique pointer.
