### ISSUE TITLE
Fiber requirements fail when cross-compiling

### ISSUE THREAD

**Issue by ClaymorePT** [boostorg/fiber#92]
If I try to cross-compile Boost.Fiber for the armv6 architecture, the cxx11_* requirements in the Jamfile.v2 will fail, because the building system will try to execute the binaries on the host.

This should not happen. 
The fact that the binaries are compiled is enough to guarantee the cxx11_* support by the compiler.

**Comment by olk** [comment]
this is a problem of boost.build - boost.build/boost.config evaluate/provide cxx11_*

**Comment by ClaymorePT** [comment]
Oh! I'm sorry then. Thank you for the enlightment. :)

Em 28/10/2016 17:55, "Oliver Kowalke" <notifications@github.com> escreveu:
